name = "stalldiary"
main = "src/worker.ts"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false
# For a custom domain, replace the example below with your own domain.
# routes = [
#   { pattern = "stalldiary.example.com", custom_domain = true }
# ]

[vars]
GITHUB_LOGIN = "your-github-login"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
